psql:
  host: 'localhost'
  database: 'mybase'
  user: 'myuser'
  passwd: 'mypass'
  port: 5432

auth:
  access_token_expiration: 5
  refresh_token_expiration: 5
  secret_words: ['Rampart', 'Necropolis', 'Tower']
  regex_for_password: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%_*\-#?&])[A-Za-z\d@$!%_*\-#?&]{6,20}$'
  regex_for_username: '^[A-Za-z][A-Za-z0-9_]{3,29}$'